version: "3"
services:

  redis-server:
    image: redis:latest
    container_name: "redis"
    command: redis-server --port 6379
    ports:
      - 6379:6379
      
  express-server:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
    ports: 
      - "3001:3001"
    environment:
      - NODE_ENV=development