version: "3"
services:

  redis-server:
    image: redis:latest
    container_name: "redis"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env.dev

  express-server:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
    ports:
      - "3001:3001"
