version: "3"
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 81:81 #관리포트
      - 80:80 #http
      - 443:443 #https
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: 'true'
    depends_on:
      - express-server
  

  redis-server:
    image: redis:latest
    container_name: "redis"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    ports:
      - 6379:6379
    env_file:
      - .env.prod
  

  express-server:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - redis-server